/**
 You have cultivated a plant, and after months of hard work, the time has come to reap the flowers of your hard work. When it was growing, you added water and
 fertilizer, and kept a constant temperature. It's time check how much your plant has grown.
 A plant is represented horizontally, from the base to the left, to the end to the right:
 ---@---@---@
 The stem is represented by hyphens -, and the flowers are represented by symbols. A plant always starts with the stem, and always ends with flowers.
 Four parameters will be given. The four parameters are:
 * @param  {string} seed - determines the type of flowers generated by the plant.
 * @param  {number} water  - each unit of water extends the portion of stem between the flowers. It also gives how many times the stems + flower clusters
 * should be repeated
 * @param  {number} fert - each unit of fertilizer increases the amount of flowers, grouped in clusters
 * @param  {number} temp - if the temperature given is in the range of 20°C and 30°C, the plant grows normally, otherwise,
 all the flowers die except for one flower at the end  of the stem.
 Given the above parameters, your task is to return a string representing the plant.
 Notes
 Edge conditions will not be tested, meaning parameters of water or fertilizer or temperature being zero. This will not be tested.
 The parameters will always be valid (no zero).
 The temperature bounds are inclusive (20 and 30 will be included as 21, 22, 23, 24...)
 * @return {string}
 */
function plant(seed, water, fert, temp) {
    let flower = '';
    if (temp > 30 || temp < 20) {
        for (let i = 0; i < water ** 2; i++) {
            flower += "-";
        }
        flower += seed;
    } else {
        for (let j = 0; j < water; j++) {
            let i = 0
            for (; i < water; i++) {
                flower += "-";
            }

            if (i === water) {

                for (let j = 0; j < fert; j++) {
                    flower += seed;
                }
            }
        }
    }
    console.log(flower)
}

plant(",", 3, 7, 25)